name: Daily Law Update

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run update script
        run: python update_index.py

      - name: Commit updated law data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add laws/ last_law.txt
          echo "Files staged for commit:"
          git diff --cached --name-only
          if ! git diff --quiet --cached; then
            git commit -m "Update latest laws JSON"
            git push
          else
            echo "No changes to commit."
