name: Daily Law Update

on:
  schedule:
    - cron: '0 19 * * *'  # Every day at 19:00 UTC (8:00 PM UK time during BST)
  workflow_dispatch:       # Manual run option

jobs:
  update-laws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run update script
        run: python update_index.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html last_law.txt
          git commit -m "Auto-update: new law(s) added" || echo "No changes to commit"
          git push
